CREATE TABLE IF NOT EXISTS market_price_bars (
    symbol VARCHAR(32) NOT NULL,
    price_date DATE NOT NULL,
    close_price DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (symbol, price_date)
);

CREATE TABLE IF NOT EXISTS market_prediction_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol VARCHAR(32) NOT NULL,
    model_type VARCHAR(32) NOT NULL,
    action VARCHAR(16) NOT NULL,
    confidence DOUBLE PRECISION,
    q_value DOUBLE PRECISION,
    last_close DOUBLE PRECISION NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    iterations INTEGER NOT NULL,
    trained_rows INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS market_q_values (
    symbol VARCHAR(32) NOT NULL,
    short_trend VARCHAR(16) NOT NULL,
    medium_trend VARCHAR(16) NOT NULL,
    volatility VARCHAR(16) NOT NULL,
    action VARCHAR(16) NOT NULL,
    q_value DOUBLE PRECISION NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (symbol, short_trend, medium_trend, volatility, action)
);
